name: bootcamp-session-2023

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installing Node Module
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install

      - name: Installing surge globally
        run: npm install -g surge

      - name: Building project
        run: npm run build

      - name: Deploying on surge
        run: surge ./build http://bootcamp2023_sess02.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
